import './globals.css'
import type { Metadata } from 'next'
import { ClerkProvider, auth } from '@clerk/nextjs'
import ThemeProvider from '@/components/theme-provider'
import { Toaster } from '@/components/ui/toaster'
import { QueryProvider } from '@/components/query-provider'
import Navbar from '@/components/navbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { userId } = auth()
  return (
    <ClerkProvider>
      <html
        lang="ko"
        className="overflow-y-hidden sm:overflow-y-auto"
        suppressHydrationWarning
      >
        <body>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <QueryProvider>
              {userId && <Navbar />}
              {children}
              <Toaster />
            </QueryProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
